// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwtonxigkaglujrwivff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3dG9ueGlna2FnbHVqcndpdmZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTQ3ODUsImV4cCI6MjA3MTI5MDc4NX0.gbUQQyjMckJdtJs8xyRIto1TtDN0kfdU4Z4lLsSohx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});